### ISSUE TITLE
[bug] CUDA not Working on GeForce RTX 5060

### ISSUE THREAD

**Issue by bam91** [alicevision/Meshroom#2950]
**Describe the bug**
When trying to use GPU enabled features(like ImageDetectionPrompt), I geht this Error in my Log and the Step fails:
RuntimeError: CUDA error: no kernel image is available for execution on the device

**To Reproduce**
1. Create Project with ImageDetectionPromt Step
2. Start Project
3. Error

**Expected behavior**
My Graphiccard has CUDA. This should work.

**Log**
```
RuntimeError: CUDA error: no kernel image is available for execution on the device

``` 

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 11
 - Qt/PySide version [e.g. 6.8.2]
 - Meshroom version: 2025.1.0
 - GeForce Driver: 576.88
 - Cuda Toolkit 12 installed

**Comment by alexgubanow** [comment]
same for me with rtx 5070.
mrSegmentation has cuda 12.4, but we need at least 12.8
updating the plugin as per https://github.com/meshroomHub/mrSegmentation/blob/main/INSTALL.md leads to:
`ImportError: Failed to load PyTorch C extensions`

**Comment by t3hchipmunk** [comment]
> same for me with rtx 5070. mrSegmentation has cuda 12.4, but we need at least 12.8 updating the plugin as per https://github.com/meshroomHub/mrSegmentation/blob/main/INSTALL.md leads to: `ImportError: Failed to load PyTorch C extensions`

I updated the plugin following your link but made the following change to the torch-requirements.txt and am not having any issues now.

```
-i https://download.pytorch.org/whl/cu128
torch==2.7.0
torchvision==0.22.*
``` #

**Comment by jwcrawley** [comment]
Same as well. I get the "RuntimeError: CUDA error: no kernel image is available for execution on the device" as well. 

Running Xubuntu 24.04
NVIDIA GeForce RTX 5060 Ti
Driver Version: 580.95.05
CUDA Version: 13.0

**Comment by yonhdee** [comment]
Same as well. running `alicevision/meshroom:2025.1.0-av3.3.0-ubuntu22.04-cuda12.1.1` on manjero
RTX5060Ti 16G
NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1

**Comment by gnbl** [comment]
I have this issue with Meshroom-2025.1.0-Linux.tar.gz on Linux Mint 22.2 Cinnamon and a RTX 5060 Ti (nvidia-driver-580-open 580.95.05).
The directory `plugins/mrSegmentation/` is a virtual environment, but activating it after changing the `bin/python` link and trying to pip install [torch-reqirements.txt](https://github.com/meshroomHub/mrSegmentation/blob/main/torch-requirements.txt) as modified by [t3hchipmunk](https://github.com/alicevision/Meshroom/issues/2950#issuecomment-3677774106), pip gives me an error about an externally managed environment.
`--break-system-packages` seems to install to `/usr/lib/python3/dist-packages/`.

Is it possible to upgrade torch and torchvision in the plugin venv?

**Comment by knobby4444** [comment]
I'm running Linux Mint 22.2 with 5070Ti 16GB and getting the error.  I was able to update mrSegmentation as above, but still getting the issue.  Ran these commands:

############
cd /opt/Meshroom-2025.1.0/plugins/mrSegmentation/
sudo apt install python3.12-venv
python3 -m venv venv
 source venv/bin/activate
vi torch-requirements.txt
## The torch-requirements.txt file was not there for me, created it as below
-i https://download.pytorch.org/whl/cu128
torch==2.7.0
torchvision==0.22.*
##
pip install -r torch-requirements.txt --upgrade --force-reinstall
##############
Install ran without errors and here is the end of the output:

#################
Installing collected packages: nvidia-cusparselt-cu12, mpmath, typing-extensions, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, triton, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch, torchvision
Successfully installed MarkupSafe-2.1.5 filelock-3.20.0 fsspec-2025.12.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 numpy-2.3.5 nvidia-cublas-cu12-12.8.3.14 nvidia-cuda-cupti-cu12-12.8.57 nvidia-cuda-nvrtc-cu12-12.8.61 nvidia-cuda-runtime-cu12-12.8.57 nvidia-cudnn-cu12-9.7.1.26 nvidia-cufft-cu12-11.3.3.41 nvidia-cufile-cu12-1.13.0.11 nvidia-curand-cu12-10.3.9.55 nvidia-cusolver-cu12-11.7.2.55 nvidia-cusparse-cu12-12.5.7.53 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.8.61 nvidia-nvtx-cu12-12.8.55 pillow-12.0.0 setuptools-70.2.0 sympy-1.14.0 torch-2.7.0+cu128 torchvision-0.22.0+cu128 triton-3.3.0 typing-extensions-4.15.0
################

Run Meshroom and try image detect prompt and get this output:

##########################
[2026-01-19 08:51:41.167969] [0x000078483de49740] [trace]   Embedded OCIO configuration file: '/opt/Meshroom-2025.1.0/aliceVision/share/aliceVision/config.ocio' found.
[QtAliceVisionImageIO] Plugin Initialized
[QtAliceVision] Plugin Initialized
Starting Process for 'ImageDetectionPrompt_1'
 - commandLine: /opt/Meshroom-2025.1.0/meshroom_compute /home/knobby/Documents/SG-Soldier.mg --node ImageDetectionPrompt_1 --extern --inCurrentEnv --iteration 0
 - logFile: /home/knobby/Documents/MeshroomCache/ImageDetectionPrompt/42c98c827ee9a46e3f1c0677cb1fe256a48f1da2/0.log
 - command full path: /opt/Meshroom-2025.1.0/meshroom_compute
ERROR:root:Error on node computation: Error on node "ImageDetectionPrompt_1(0)":
Log:
[08:51:55.404][info] Chunk range from 0 to 49
info:ImageDetectionPrompt_1:Chunk range from 0 to 49
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`
[2026-01-19 08:51:59.112940] [0x00007b0e8548eb80] [debug]   [IO] Read Image: /home/knobby/Pictures/SgGonzales/Soldier/darktable_exported/DSC04058.jpg
[2026-01-19 08:51:59.151304] [0x00007b0e8548eb80] [trace]   Detected image color space: sRGB
[2026-01-19 08:51:59.151328] [0x00007b0e8548eb80] [trace]   Read image /home/knobby/Pictures/SgGonzales/Soldier/darktable_exported/DSC04058.jpg (encoded in sRGB colorspace).
INFO:root: - elapsed time: 0:00:05.711590
Traceback (most recent call last):
  File "/usr/local/lib64/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 47, in run
  File "bin/meshroom_compute", line 101, in <module>
  File "/opt/Meshroom/meshroom/core/node.py", line 502, in process
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/meshroom/imageSegmentation/ImageDetectionPrompt.py", line 201, in processChunk
    bboxes, conf, tags = processor.process(image = img,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/segmentationRDS/segmentation.py", line 378, in process
    recoOK, tags = self.recognize(wordlist, image, verbose)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/segmentationRDS/segmentation.py", line 325, in recognize
    tags = self.get_tags(image)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/segmentationRDS/segmentation.py", line 315, in get_tags
    res = inference(ram_image.to(self.DEVICE), self.ram)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/ram/inference.py", line 36, in inference_ram
    tags, tags_chinese = model.generate_tag(image)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/ram/models/ram_plus.py", line 284, in generate_tag
    image_embeds = self.image_proj(self.visual_encoder(image))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/ram/models/swin_transformer.py", line 563, in forward
    x = self.patch_embed(x)
        ^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/ram/models/swin_transformer.py", line 448, in forward
    x = self.proj(x).flatten(2).transpose(1, 2)  # B Ph*Pw C
        ^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Meshroom-2025.1.0/plugins/mrSegmentation/lib64/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
################################

I'm running mint versions of nvidia drivers, not on cuda 12.8:

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

NVIDIA Driver Version: 580.95.05

**Comment by knobby4444** [comment]
I tried installed Debian 13.1 with nvidia drivers installed like this: https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/debian.html and have cuda 13.1.  Unfortunately it appears 13.1 is not yet supported by pytorch.  I see 13.0 but not yet 13.1 here:  https://download.pytorch.org/whl/.  Have not yet found a way to downgrade cuda to 13.0.

**Comment by hryamzik** [comment]
Looks like all 50xx cards are affected, I get the same on 5080 and windows 11, looking forward to see a new build with a fresh CUDA version.

**Comment by 1e100** [comment]
This seems extra flaky because it did actually work for me on a 5090 a month ago, but does not work now even if I provide CUDA_HOME to point to cuda-12. Previously however, I was using it for things that do not require PyTorch - just plain photogrammetry. Now I'm trying to use it for turntable photogrammetry.

**Comment by MarcosRRM** [comment]
Having the same problem on Windows 11 25H2 with a RTX 5090.

**Comment by brosequist** [comment]
I opened a draft PR in the bundled segmentation plugin that targets this RTX 50-series failure: https://github.com/meshroomHub/mrSegmentation/pull/50

The issue appears to be that the plugin's optional GPU requirements currently install PyTorch CUDA 12.4 wheels, which can expose CUDA but do not include kernels for RTX 50-series / Blackwell devices. The PR updates the optional GPU requirements to PyTorch CUDA 12.8 and adds a CUDA architecture guard so unsupported PyTorch builds fall back with a clear message instead of failing later with `no kernel image is available for execution on the device`.

**Comment by seebeck88** [comment]
I had the same problem, I'm not an expert so the terminology I use can be no the right one  but I'll explain what I think is the issue, and how I solved it. I also have  RTX50 series 

Mesroom comes with its own Python 3.11 and PyTorch 2.5.1 that version of PyTorch needs CUDA 12.4. The problem is RTX 50s only works with versions of CUDA 12.8 and higher, the latest CUDA version that Meshroom can use is 12.9, so basically you can use only 12.8 and 12.9 CUDA tool kit versions, but if you install CUDA 12.8 or 12.9 + PyTorch 2.8.0  Meshroom won't be able to reach PyTorch because PyTorch is just installed for the Python on your system not for the Python  Meshroom comes with, so you need to also install the PyTorch library for the Python Meshroom use. 

Install Pytorch was kind of a challenge for me because I'm not familiar with how Python works and I has to do some quick research to learn the basics and install PyTorch.  So if is your case to there are a lot of tutorials out there about how to do it. this video help me a lot  https://www.youtube.com/watch?v=ibS3My-nbhc  in the video explains how to install CUDA, PyTorch and cuDNN, I didn't installed that last one since I didn't think it was a Meshroom requirement. In the part of the video that explains how to choose PyThor don’t use the chart since it won't show the 12.8 or 12.9 version, below the chart there is an option that says "Previous versions of PyTorch"  click there then look for the version 12.8 or 12.8 for  for windows and Linux. and use that command instead of the command they use in the video.  

The fix 

-First, I recommend you install the same version of Python that comes with Meshroom that is 3.11, Meshroom use its own Python  

-Second, you need  to match Pytorch and CUDA  version, Meshroom only support until CUDA 12.9 soy download and install the CUDA took kit 12 version you want and then you need to install the PyTorch version that match that version of CUDA
 
Example for CUDA 12.9 
"pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu129"



-Third, Meshroom comes with is own Python so when I was trying to solve the problem I test a lot of versions of CUDA and Pytorch but even before running the test successfully and be sure everything was good, it didn't solve the problem, in that point I figured out the problem was Meshroom was not able to reach PyTorch, so I inspect the folders on Meshroom looking for clues, and I found a Torch library on this address:

"Meshroom-2025.1.0\plugins\mrSegmentation\venv\Lib\site-packages"

 and also found a folder with the same name on the Python installed on my system with this address: 

"Python311\Lib\site-packages"

  So  I copied the  "site-packages" from the Python installed on my system and paste and merge it with the "site-packages" inside Meshroom. 

That was how I solve it. 

As I said before I'm not an expert of any kind but my intuition told me "if I can't install Torch directly in the Python Meshroom use, maybe I can put it there manually"  and it work.  


I also learn that the folder "Meshroom-2025.1.0>plugins>mrSegmentation>venv"  contains a Python environment or wherever is the right terminology, though you can't run this Python.exe, because in the venv folder there is a file name Pyvenv this file is creates when Meshroom is packed an it is linked to the python folder that was the machine it was packed in so if you try to run with cmd Python won't finde the way home so I put the right address on that file and I was able to run a successful test with the Python that comes with Meshroom.  I could've provably installed PyTorch if I could've learned how to run the Python Meshroon use  before using the copy paste folder method but as it worked I didn't touch anything after that. 

It might not be the most orthodox way to do but it worked.

**Comment by servandoa** [comment]
### Environment Setup & Fix for RTX 50-Series (Blackwell `sm_120`) & Plugin Runtime Issues

If you are trying to run PyTorch-based ML nodes (such as `mrSegmentation`) on newer NVIDIA hardware (e.g., RTX 5060 Ti / RTX 50-series) or encountering Python import crashes during node computation in Meshroom, here is what worked to get everything running cleanly:

---

#### 1. Blackwell Architecture (`sm_120`) Support via PyTorch Nightly (CUDA 13.2)

Standard PyTorch stable wheels (`cu124`) only ship with pre-compiled kernels up to `sm_90` (Hopper), triggering:
```text
UserWarning: NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
I have created a new virtual environment using uv with python3.11 on a separate folder, deleted the bin, lib of the `/path/to/Meshroom/plugins/mrSegmentation`, created symbolic links to the files of the new environment.
`ln -s new_env/* /path/to/Meshroom/plugins/mrSegmentation`

[requirements-lock.txt](https://github.com/user-attachments/files/32419016/requirements-lock.txt)

Install the requirements in the environment:
`uv pip install -r requirements.txt`

Note: The environment requires PyTorch  built against CUDA 13.2 (--index-url https://download.pytorch.org/whl/cu132) for sm_120 kernel support, along with transformers<4.41.0,>=4.38.0 and graphlib-backport.

Check here for newer versions: https://pytorch.org/get-started/locally/


## Patching for errors in the frozen distribution

I was getting also an error of ctypes, it was pointing to one of the pyc files of the frozen distribution outside the environment, to solve it.

In the `/path/to/Meshroom/plugins/mrSegmentation/meshroom/imageSegmentation/ImageDetectionPrompt.py`, before importing the meshroom modules:

```python
import sys
import ctypes
import types

# 1. Patch ctypes.wintypes for Linux frozen environments
if "ctypes.wintypes" not in sys.modules:
    wintypes_mock = types.ModuleType("ctypes.wintypes")
    wintypes_mock.DWORD = ctypes.c_ulong
    wintypes_mock.WORD = ctypes.c_ushort
    wintypes_mock.BYTE = ctypes.c_ubyte
    wintypes_mock.BOOL = ctypes.c_int
    wintypes_mock.LPCWSTR = ctypes.c_wchar_p
    sys.modules["ctypes.wintypes"] = wintypes_mock

# 2. Patch ctypes.util for missing frozen module
if "ctypes.util" not in sys.modules:
    util_mock = types.ModuleType("ctypes.util")
    util_mock.find_library = lambda name: None
    sys.modules["ctypes.util"] = util_mock
    ctypes.util = util_mock
```

I think that I put all that I had to do to make it run.
